"""Offline 3D structures and free-amino-acid constants for Protein Atlas.

The descriptive reference table (names, families, masses, SMILES, PubChem ids,
hydrogen-bond roles ...) lives in atlas_engine.py.  This module adds two things
that table does not have:

  * 3D coordinates and bonds for all 20 L-amino acids
    (data/amino_acid_structures.json, generated by
    tools/build_amino_acid_structures.py), served as an MDL molfile so the
    interactive viewer always works - with or without internet access.
  * The free-amino-acid pK1 / pK2 / pKR values and the isoelectric point
    derived from them (Nelson & Cox, Lehninger Principles of Biochemistry,
    Table 3-1, 25 degC).  These describe the *free* amino acid and are
    deliberately labelled as such; protein pI in Atlas uses the EMBOSS set.

Formula and atom/bond counts are derived from the molecular graph itself, so
the 3D model and the numbers shown next to it cannot disagree.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

import protein_analyzer as pa

DATA_FILE = Path(__file__).resolve().parent / "data" / "amino_acid_structures.json"

# average and monoisotopic atomic masses
AVG = {"H": 1.008, "C": 12.011, "N": 14.007, "O": 15.999, "S": 32.06}
MONO = {"H": 1.00782503, "C": 12.0, "N": 14.0030740, "O": 15.9949146, "S": 31.9720707}

PK = {  # code: (pK1 alpha-COOH, pK2 alpha-NH3+, pKR side chain or None)
    "G": (2.34, 9.60, None), "A": (2.34, 9.69, None), "V": (2.32, 9.62, None),
    "L": (2.36, 9.60, None), "I": (2.36, 9.68, None), "M": (2.28, 9.21, None),
    "P": (1.99, 10.96, None), "F": (1.83, 9.13, None), "W": (2.38, 9.39, None),
    "S": (2.21, 9.15, None), "T": (2.09, 9.10, None), "C": (1.96, 10.28, 8.18),
    "Y": (2.20, 9.11, 10.07), "N": (2.02, 8.80, None), "Q": (2.17, 9.13, None),
    "D": (1.88, 9.60, 3.65), "E": (2.19, 9.67, 4.25), "K": (2.18, 8.95, 10.53),
    "R": (2.17, 9.04, 12.48), "H": (1.82, 9.17, 6.00),
}
# side chain group that carries the pKR (for display)
PKR_GROUP = {"C": "thiol (\u2013SH)", "Y": "phenol (\u2013OH)", "D": "\u03b2-carboxyl",
             "E": "\u03b3-carboxyl", "K": "\u03b5-ammonium", "R": "guanidinium",
             "H": "imidazolium"}
ACIDIC_PKR, BASIC_PKR = {"C", "Y", "D", "E"}, {"K", "R", "H"}


@lru_cache(maxsize=1)
def _structures() -> dict[str, Any]:
    return json.loads(DATA_FILE.read_text(encoding="utf-8"))


def _graph(code: str):
    entry = _structures()[code]
    elements = [a[0] for a in entry["atoms"]]
    adjacency: dict[int, list[tuple[int, int]]] = {i: [] for i in range(len(elements))}
    for a, b, order in entry["bonds"]:
        adjacency[a].append((b, order))
        adjacency[b].append((a, order))
    return elements, adjacency


def _formula_counts(elements: list[str]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for el in elements:
        counts[el] = counts.get(el, 0) + 1
    return counts


def _formula_text(counts: dict[str, int]) -> str:
    out = ""
    for el in ("C", "H", "N", "O", "S"):
        if counts.get(el):
            out += el + (str(counts[el]) if counts[el] > 1 else "")
    return out


def _isoelectric_point(code: str) -> float:
    pk1, pk2, pkr = PK[code]
    if code in ("D", "E", "C"):
        return (pk1 + pkr) / 2
    if code in ("K", "R", "H"):
        return (pk2 + pkr) / 2
    return (pk1 + pk2) / 2


def extras(code: str) -> dict[str, Any]:
    """Free-amino-acid constants and graph-derived counts for one residue."""
    code = code.upper()
    if code not in pa.AMINO_ACIDS:
        raise KeyError(code)
    elements, _ = _graph(code)
    counts = _formula_counts(elements)
    pk1, pk2, pkr = PK[code]
    return {
        "code": code,
        "pk1": pk1, "pk2": pk2, "pkr": pkr,
        "pkr_group": PKR_GROUP.get(code),
        "isoelectric_point_free": round(_isoelectric_point(code), 2),
        "pk_source": "Nelson & Cox, Lehninger Principles of Biochemistry (free amino acid, 25 \u00b0C)",
        "model_formula": _formula_text(counts),
        "heavy_atoms": sum(1 for e in elements if e != "H"),
        "atoms_total": len(elements),
        "bonds_total": len(_structures()[code]["bonds"]),
        "stereo": ("Achiral" if code == "G"
                   else "L (2S, 3S)" if code == "I"
                   else "L (2S, 3R)" if code == "T"
                   else "L (2R)" if code == "C" else "L (2S)"),
    }


def sdf(code: str) -> str:
    """MDL V2000 molfile for the 3D model (neutral, free amino acid)."""
    code = code.upper()
    entry = _structures()[code]
    lines = [pa.AMINO_ACID_NAMES[code], "  ProteinAtlas 3D", "",
             f"{len(entry['atoms']):3d}{len(entry['bonds']):3d}  0  0  1  0  0  0  0  0999 V2000"]
    for el, x, y, z in entry["atoms"]:
        lines.append(f"{x:10.4f}{y:10.4f}{z:10.4f} {el:<3} 0  0  0  0  0  0  0  0  0  0  0  0")
    for a, b, order in entry["bonds"]:
        lines.append(f"{a + 1:3d}{b + 1:3d}{order:3d}  0")
    lines.append("M  END")
    return "\n".join(lines) + "\n$$$$\n"


def structure(code: str) -> dict[str, Any]:
    code = code.upper()
    entry = _structures()[code]
    return {"format": "sdf", "data": sdf(code),
            "atoms": [a[0] for a in entry["atoms"]],
            "source": "Protein Atlas built-in model",
            "note": "Neutral (non-zwitterionic) free amino acid, L-configuration. Coordinates come from "
                    "a restraint-based embedding validated for bond lengths, angles, planarity, "
                    "clashes and stereochemistry; they are a clean model, not an experimental structure."}
